### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by erdnaxel** [gadenbuie/ggpomological#23]
i tried installing the package, but getting the error:

ERROR: lazy loading failed for package 'ggpomological'

Error: Failed to install 'ggpomological' from GitHub:
  (converted from warning) installation of package ‘C:XXXXX/Local/Temp/Rtmp8IitAF/file53005ea93e4e/ggpomological_0.1.2.tar.gz’ had non-zero exit status

I installed all the dependencies, didn't help.

**Comment by gadenbuie** [comment]
I'm sorry, this isn't really enough information for me to help you diagnose the problem. I just tried installing the package locally in a few R versions and it worked as expected. I'm going to close this for now but please feel free to add any additional information you can provide.
